DesignPatternsAsp/Models/ErrorViewModel.cs
namespace DesignPatternsAsp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DesignPatternsAsp/Models/ViewModels/BeerViewModel.cs
namespace DesignPatternsAsp.Models.ViewModels
{
    public class BeerViewModel
    {
        public int Id { get; set; }

        public string Name { get; set; } 

        public string Style { get; set; }
    }
}

DesignPatternsAsp/Models/ViewModels/FormViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace DesignPatternsAsp.Models.ViewModels
{
    public class FormViewModel
    {
        [Required]
        public string Name { get; set; }
        [Required]
        public string Style { get; set; }
        public int? BrandId{ get; set; }

        [Display(Name = "Otra marca")]
        public string OtherBrand { get; set; }
    }
}

DesignPatternsAsp/Controllers/BeerController.cs
using DesignPatternsAsp.Models.ViewModels;
using DesignPatternsAsp.Strategies;
using DesingPatterns.Models.Data;
using DesingPatterns.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace DesignPatternsAsp.Controllers
{
    public class BeerController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public BeerController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            IEnumerable<BeerViewModel> beers = from beer in _unitOfWork.Beers.GetAll()
                                               select new BeerViewModel
                                               {
                                                   Id = beer.BeerId,
                                                   Name = beer.Name,
                                                   Style = beer.Style
                                               };

            return View("Index", beers);
        }

        [HttpGet]
        public IActionResult Add()
        {
            GetBrands();
            return View();
        }

        [HttpPost]
        public IActionResult Add(FormViewModel beerVM)
        {

            if (!ModelState.IsValid)
            {
                GetBrands();
                return View("Add", beerVM);
            }

            var context = beerVM.BrandId == null ? 
                  new BeerContext (new BeerStrategy()) : 
                  new BeerContext(new BeerWithBrandStrategy());
           
            context.Add(beerVM, _unitOfWork);

            return View("Create", beerVM);
        }

        #region HELPERS 
        private void GetBrands()
        {
            var brands = _unitOfWork.Brands.GetAll();
            ViewBag.Brands = new SelectList(brands, "BrandId", "Name");
        }
        #endregion
    }
}

DesignPatternsAsp/Controllers/GeneratorFileController.cs
using DesingPatterns.Repository;
using Microsoft.AspNetCore.Mvc;
using Tools.Generator;

namespace DesignPatternsAsp.Controllers
{
    public class GeneratorFileController : Controller
    {
        private IUnitOfWork _unitOfWork;
        private GeneratorConcreteBuilder _generatorConcreteBuilder;
        public GeneratorFileController(IUnitOfWork unitOfWork, GeneratorConcreteBuilder generatorConcreteBuilder)
        {
            _unitOfWork = unitOfWork;
            _generatorConcreteBuilder = generatorConcreteBuilder;
        }

        public IActionResult Index()
        {

            return View();
        }

        public IActionResult CreateFile(int optionFile)
        {
            try
            {
                //obtener la lista de cervezas
                var beer = _unitOfWork.Beers.GetAll();
                List<string> content = beer.Select(x => x.Name).ToList();

                //generar el archivo
                string path = "file" + DateTime.Now.Ticks + new Random().Next(100)+".txt";
                //Llamamos al director
                var generatorDirector = new GeneratorDirector(_generatorConcreteBuilder);

                //Creamos el generador dependiendo de la opción
                if (optionFile == 1)
                    generatorDirector.CreateSimpleJsonGenerator(content, path);
                else 
                    generatorDirector.CreateSimplePipeGenerator(content, path);

                //Ejecutamos el generador y lo guardamos
                var generator = _generatorConcreteBuilder.GetGenerator();
                generator.Save();
                
                return Json("Archivo generado ");

            } catch (Exception)
            {
                return BadRequest();
            }
        }
    }
}

DesignPatternsAsp/Controllers/HomeController.cs
using DesignPatternsAsp.Configuration;
using DesignPatternsAsp.Models;
using DesingPatterns.Models.Data;
using DesingPatterns.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using System.Diagnostics;
using Tools;

namespace DesignPatternsAsp.Controllers
{
    public class HomeController : Controller
    {
        private readonly IOptions<MyConfig> _config;

        //declaramos el repositorio
        private readonly IRepository<Beer> _repository;

        //inyectamos el repositorio en el constructor
        public HomeController(IOptions<MyConfig> config, IRepository<Beer> repository)
        {
            _config = config;
            _repository = repository;
        }


        public IActionResult Index()
        {
            //obtenemos todas las cervezas
            IEnumerable<Beer> beers = _repository.GetAll();
            return View("Index", beers);
        }

        public IActionResult Privacy()
        {
            Log.GetInstance(_config.Value.Pathlog).Save("Entro a privacidad");
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DesignPatternsAsp/Controllers/ProductDetailController.cs
using Microsoft.AspNetCore.Mvc;
using Tools.Earn;
using Tools.Earn.ForeingEarnExtra;

namespace DesignPatternsAsp.Controllers
{
    public class ProductDetailController : Controller
    {
        private EarnFactory _earnFactory;
        public ProductDetailController(EarnFactory earnFactory)
        {
            _earnFactory = earnFactory;
        }
        public IActionResult Index(decimal total)
        {
            //Aplicamos la inyección de dependencias
            var localEarnID = _earnFactory.GetEarn();
            var foreingEarnID = _earnFactory.GetEarn();


            //use products
            ViewBag.totalLocal = total + localEarnID.Earn(total);
            ViewBag.totalForeing = total + foreingEarnID.Earn(total);

            return View();
        }
    }
}

DesignPatternsAsp/Views/Beer/Add.cshtml
@model DesignPatternsAsp.Models.ViewModels.FormViewModel

<form asp-controller="Beer" asp-action="Add" method="post">

    <div class="form-group">
        <label asp-for="Name"></label>
        <input class="form-control" asp-for="Name" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Style"></label>
        <input class="form-control" asp-for="Style" />
        <span asp-validation-for="Style" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="BrandId"></label>
        <select class="form-control" asp-for="BrandId" asp-items="@ViewBag.Brands">
            <option value="">--- Selecciona marca ---</option>
        </select>
        <span asp-validation-for="BrandId" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="OtherBrand"></label>
        <input class="form-control" asp-for="OtherBrand" />
        <span asp-validation-for="OtherBrand" class="text-danger"></span>
    </div>

    <div class="form-group">
        <button class="btn btn-primary" type="submit">Guardar</button>
    </div>
</form>

DesignPatternsAsp/Views/Beer/Index.cshtml
@using DesignPatternsAsp.Models.ViewModels;
@model IEnumerable<BeerViewModel>

<a class="btn btn-primary" href="~/Beer/Add">Add Beer</a>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.First().Name)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var beer in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => beer.Name)
                </td>

            </tr>
        }
    </tbody>
</table>

DesignPatternsAsp/Views/GeneratorFile/Index.cshtml
<div class="row">
    <div class="col-8 offset-2">
        <div class="form-group">
            <select id="optionFile">
                <option value="1">Json</option>
                <option value="2">Pipple</option>
            </select>
        </div>
        <div class="form-group">
            <button class="btn btn-success" onclick="generate();">Generar</button>
        </div>
    </div>
</div>

<script>
    function generate(){
        let optionFile = document.getElementById("optionFile").value;
        fetch("@Url.Content("~/GeneratorFile/CreateFile")" + "?optionFile=" + optionFile)
            .then(res => res.json())
            .then(json => alert(json));
    }
</script>

DesignPatternsAsp/Views/Home/Index.cshtml
@using DesingPatterns.Models.Data;
@model IEnumerable<Beer>
@{
    ViewData["Title"] = "Home Page";
}

@foreach (var item in Model)
{
    <div>
        <h4>@item.Name</h4>
    </div>
}

DesignPatternsAsp/Views/ProductDetail/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    decimal totalLocal = (decimal)ViewBag.totalLocal;


}

<p>Total: @totalLocal</p>

DesignPatternsAsp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DesignPatternsAsp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DesignPatternsAsp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DesignPatternsAsp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - DesignPatternsAsp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>